import { GetStaticPaths, GetStaticProps } from "next";
import Head from "next/head";
import React from "react";
import { CourseInterface } from "../../components/elements/CourseCard";
import PageTitle from "../../components/elements/PageTitle";
import RelatedCourses from "../../components/elements/RelatedCourses";
import CourseDetailPage from "../../components/templates/CourseDetailPage";

interface Props {
  course: CourseInterface;
  related_courses: CourseInterface[];
}

const CoursesDetail: React.FC<Props> = ({ course, related_courses }) => {
  return (
    <div>
      <Head>
        <title>Courses Detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTitle title={course.title} content={course.excerpt} />

      <CourseDetailPage course_data={course} />

      <RelatedCourses related_courses={related_courses} />
    </div>
  );
};

export const getStaticPaths: GetStaticPaths = async () => {
  const res = await fetch("https://next-workshop-backend-01.herokuapp.com/courses");
  const courses: CourseInterface[] = await res.json();

  const paths = courses.map(c => ({
    params: {
      id: c.id,
    },
  }));

  return {
    paths,
    fallback: false, // every other route which will fall out of the paths above will result in a 404 page
  };
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  if (params) {
    const res = await fetch(`https://next-workshop-backend-01.herokuapp.com/courses/${params.id}`);
    const course = await res.json();

    const resCourses = await fetch("https://next-workshop-backend-01.herokuapp.com/courses");
    const courses = await resCourses.json();

    // courses length 10 - we always want to show the next 3 items, so we limit the number to 7
    const randomNo = Math.floor(Math.random() * (courses.length - 3));
    const resRelated = await fetch(`https://next-workshop-backend-01.herokuapp.com/courses?_start=${randomNo}&_limit=3`);
    const related_courses = await resRelated.json();

    return {
      props: {
        course,
        related_courses,
      },
    };
  }

  return {
    props: {},
  };
};

export default CoursesDetail;
