import { GetStaticProps } from "next";
import Head from "next/head";
import React from "react";
import CourseCard, { CourseInterface } from "../../components/elements/CourseCard";
import PageTitle from "../../components/elements/PageTitle";

interface Props {
  courses_page: {
    title: string;
    first_content_block: string;
  };
  courses: CourseInterface[];
}

const CoursesOverview: React.FC<Props> = ({ courses_page, courses }) => {
  return (
    <div>
      <Head>
        <title>Courses Overview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTitle title={courses_page.title} content={courses_page.first_content_block} />

      <section className="section">
        <div className="container">
          <div className="row">
            {courses.map(c => (
              <CourseCard key={c.id} course_data={c} />
            ))}
          </div>
        </div>
      </section>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch("https://next-workshop-backend-01.herokuapp.com/courses_page");
  const courses_page = await res.json();

  const resCourses = await fetch("https://next-workshop-backend-01.herokuapp.com/courses");
  const courses = await resCourses.json();

  return {
    props: {
      courses_page,
      courses,
    },
  };
};

export default CoursesOverview;
